# Key của người dùng IAM có quyền gọi Step Functions
AWS_ACCESS_KEY = "AKIARTPXWHTYDWWCJLX6"
AWS_SECRET_KEY = "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"

# Cái ARN ông vừa copy từ Step Functions lúc nãy
SFN_ARN = "arn:aws:states:ap-southeast-1:110577990896:stateMachine:APIFlow_MultiAgent_Orchestration"